name: eduinfo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # âœ… Tambahkan package ini untuk menyimpan data lokal seperti status login
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/globe_icon.png
    - assets/google_icon.png
    - assets/facebook_icon.png
    - assets/karate.jpg
    - assets/program1.jpg
    - assets/program2.jpg
    - assets/program3.jpg
    - assets/icons.person.png
    - assets/icons.articles.png
    - assets/icons.description.png
    - assets/icons.home.png
    - assets/icons.photo_camera.png
    - assets/icons.search.png
    - assets/news1.jpg
    - assets/news2.jpg
    - assets/news3.jpg
    - assets/magnifier.png
